### ISSUE TITLE
Task:  Sprint 1 Retrospective, Sprint 2 Planning

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#12]
EPIC:  #10 

As a **scrum master/developer** I can **follow Agile principles** so that **project functionality is achieved incrementally across sprints**

### Assumptions or Pre-Requisites:
* Agile methodology is being followed for this project
* Closing out (weekly) sprint should be done with a retrospective
* Planning of next sprint should be done with backlog grooming and deciding which tasks to move to 'to do' for this sprint
* Respect timeboxing and not try to complete any tiny outstanding items from previous Sprint 'quickly' in the new Sprint. The time has passed so now deal with any hangover items in CURRENT sprint

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
* Sprint1 closed off (this happens automatically when using iterations)
* Any issues which were linked to Sprint1 but not in 'Done' status reviewed and
moved to next sprint for completion of outstanding tasks
* OR if the acceptance criteria is met and tasks done, but there are issues, then log the issues as a bug and closeout the original UserStory/ task

### Tasks

- [x] Task1 Retrospective
- [x] Task2 Backlog groominig
- [x] Task3 Sprint Planning and issue prioritisation
- [x] Task4 Update readme with work to date

**Comment by DeeMcCart** [comment]
Sprint1 was Monday 22/01 to end of day Sunday 29/01
Boundaries a bit blurred in this first sprint review, as there are a number of almost-completed issues (mainly around UserProfile and AllAuth customisation).  Continued working on these Monday 29/01 even though these are Sprint1 issues.

Total elapsed SPs (hours) Sprint1:

**Comment by DeeMcCart** [comment]
**Task 2 Planning next Sprint:**
bit of chicken-and-egg here as the first task was to gather & formalise a list of user stories #14 
from this have prioritised the basket & checkout functionality for Sprint2, these are created under issues  (EPIC) and (Issues)
