### ISSUE TITLE
User Story: List of User Stories

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#14]
EPIC:  #10 

As a **role** I can **capability** so that **received benefit**

### Assumptions or Pre-Requisites:
* This list of user stories doesn't have to be comprehensive, it just needs to be a decent attempt
* Other user stories can be added as needed when the project develops incrementally
* These user stories will be assessed and prioritised at the start of each sprint.  Some will turn out to be future requirements (ie not delivered in version1) & can be assigned the 'wont have' prioritisation if so.

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Create list of user stories for FTU (first time user), RU (returning user), SA/SO (System Admin, System Owner)
- [ ] Create an issue per user story so that the project backlog can be managed & prioritised

### Tasks

- [ ] Task1 Create list of user stories in comments below
- [ ] Task2 Separate into themes/EPICs and create a user story per EPIC
- [ ] Task3 Create an issue per user story needed for next Sprint (Sprint2)

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
**FTU**: (This could be a casual user, or a regular user without a profile)
FTU_01:  As a first time user I want to understand the site purpose and what I can do here
FTU_02:  As a first time user I want to be able to navigate
FTU_03:  As a first time user I want a responsive site, which I can use on a device of my choosing (mobile, tablet, laptop, desktop)
FTU_04:  As a first time user I want to be able to see a range of products which are offered by the Jeweller, to see pictures and descriptions for each item
FTU_05:  As a first time user I want to be able to filter my selection based on what I'm interested in (particular metals, stones, colours, particular occasions)
FTU_06: As a first time user I would like to be able to see items that are related to the item I'm interested in (e.g. earrings may have matching necklace or bracelet)
FTU_07:  As a first time user I want to understand whether an item is in-stock, made-to-order and what are lead times (e.g. available now, lead time 6 weeks for make-to-order, lead time 1 week for casted items)
FTU_08: As a first-time user I would like to receive suggestions or prompts for particular occaisons (which could be date-related e.g. communions, confirmations, mothers day, christmas)
FTU_09:  As a first time user I want to be able to share a item I like with a 3rd party (e.g. via whatsapp, fb etc)
FTU_10:  As a first-time user I would like to be able to create a first order and pay for it as a guest user on the website
FTU_11: As a first-time user I would like to be able to personalise my order, e.g. with gift card, wrapping etc
FTU_12: As a first-time user I would like to create a profile (and have the option of signing up for newsletter communication)
FTU_13: As a first-time user I would like to complete an enquiry form
FTU_14: Blog
FTU_15: FAQ
FTU_16: Make an appointment for engagement rings

**RU** Returning User
RU_01:  As a returning user I would like to be able to personalise my profile (avatar image, birth_month, delivery addresses etc)
RU_02: As a RU I would like to be able to assign delivery address(es) to my account
RU_03: Raise an order for delivery 

**SO/ SA (System owner/system Admin):
SO_01
SO_02
SO_03

**Comment by DeeMcCart** [comment]
**RU Returning User**
RU_01:  As a returning user I would like to be able to personalise my profile (avatar image, birth_month, delivery addresses etc)
RU_02: As a RU I would like to be able to assign delivery address(es) to my account
RU_03: Raise an order for delivery 

**SO/ SA (System owner/system Admin):**
SO_01
SO_02
SO_03

**Comment by DeeMcCart** [comment]
**SO/ SA (System owner/system Admin):**
SO_01
SO_02
SO_03

**Comment by DeeMcCart** [comment]
Mon 29/01/24 - reasonable attempt at user stories list.  Also tracking in Google sheets https://docs.google.com/spreadsheets/d/1aXeiYbk9_PgzvHSIGx80ogcJJJiUhq2V6vYMjumK4FY/edit#gid=528552962

**Comment by DeeMcCart** [comment]
Task 2/3 Create user stories for Sprint2 - Done - however will need to create remainder of user stories and assign to Sprint3, Sprint4
