### ISSUE TITLE
User Story: FTU_XX Integrate Toast Messaging

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#15]
EPIC:  #

As a **role** I can **capability** so that **received benefit**

### Assumptions or Pre-Requisites:
* Toast Messaging Installed #3 
* Allauth installed #4

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must receive appropriate feedback messages based on allauth activities (register, login, signout, password reminder sent etc)
- [ ] Methods for adding Toast messaging to other functions (order confirmation etc) are clear and can be tested

### Tasks
- [ ] Task1 Configure allauth to send toast messages
- [ ] Task2 Test the appropriate sending of messages for AllAuth activities
- [ ] Task3 Check/ensure that toast messaging can be used within other functions

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
**User signout:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/c252f51a-16c9-4620-84ad-082cae67ccf3)


**Confirmation of User Signout:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/1c079812-6ca6-4b09-ba4c-aa8fe5681263)
