### ISSUE TITLE
User Story: FTU_15 Shopping Basket

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#17]
EPIC:  #16 

* FTU_15: As a **First-Time User** I want to **create a shopping basket of items** in order to **determine price**

### Assumptions or Pre-Requisites:
*  The products app skeleton exists
*
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] User must be able to select one or more products and add them to a basket
- [ ] Grand total shown on top navbar must increment according to basket contents

### Tasks

- [ ] Task1  Build up Product app/Models sufficeintly to allow order processing for at least 1 product
- [ ] Task2 Build Basket app 
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
05/02/24 DONE - User can successfully create a shopping basket
