### ISSUE TITLE
User Story: FTU_16 Shopping basket - amend

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#18]
EPIC:  #16 

* FTU_16: As a **First-Time User** I want to **amend or remove items in my shopping basket** in order to **determine price**

### Assumptions or Pre-Requisites:
* Shopping basket functionality in place
* + - buttons in place
* Update Remove links in place

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must repond appropriately to + - buttons
- [x] Must not be able to use - anymore once product's basket qty = 1
- [x] Update link must reflect the choice made
- [x] Remove link must reflect the choice made
- [x] Appropriate Toasts must be shown for 'Update' and 'Remove' actions.

### Tasks

- [x] Task1 Add appropriate HTML/ JS
- [x] Task2 Test it
- [x] Task3 Prove functionality is working and so are Toasts

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion
