### ISSUE TITLE
User Story: FTU_17 Create checkout order from basket

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#19]
EPIC:  #16 

* FTU_17: As a **First-Time User** I want to **convert my shopping basket into a collection order** in order to **purchase items** 

### Assumptions or Pre-Requisites:
* Basket funtionality must exist Issue#

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Create order from basket
- [x] Order is assigned a sequential order number
- [ ] Order correctly reflects the details entered by user at checkout

### Tasks

- [x] Task1 Create Order Models Views Templates
- [x] Task2 Create custom order number generator #22 
- [x] Task3 Work through Stripe functionality for checkout order
- [x] Task4 Up to the point of creating an order and saving to database

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
DMcC 05/02/24 Yep working on this but have an issue with the order total not showing as expected, it saves as 0 even though the total verified with Stripe is correct

**Comment by DeeMcCart** [comment]
** User receives order confirmation:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/46278cd2-17a4-4c86-a551-3a9f71c6fdd0)

**Payment goes through to (test) Stripe:**


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/aa4ad401-5b6c-4ff0-982d-38e55e17ac0a)
