### ISSUE TITLE
Task:  Setup repo/ workspace/ core site html and css

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#2]
EPIC:  #1 

As a **role** I can **capability** so that **received benefit**

### Assumptions or Pre-Requisites:
n/a

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- Github Repo created; 
- Github Project and Agile settings installed
- Gitpod workspace created, Python installed, django installed
- allauth installed and first app created

### Tasks

- [x] Create ithub Repo created 
- [x] Setup Github Project, labels-sprints-milestones-kanban board etc
- [x] Create Gitpod workspace, install Python, install django
- [x]  Install allauth installed and create first app
- [x] Create 'home' app
- [x] Build basic html/ css site skeleton 

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Done 22-23/01/24

**Comment by DeeMcCart** [comment]
Returned to this Sunday 28/01; added foter with social links; worked on responsiveness.
XS S M:  Compressed navbar (with search icon and dropdown to search field) & hamburger filters 
L XL: wider navbar (with a full field for search button) with sub-navbar showing filter categories leading to drop down menus per filter cat

**XS S M:** 




**L, XL:**
