### ISSUE TITLE
User Story: FTU_18 Personalise order at checkout

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#20]
EPIC:  #48 

FTU_18: As a **First-Time User** I want to **personalise my order** to **reflect gift messages, special wrapping etc**

### Assumptions or Pre-Requisites:
* Basic Order flow is established and functional (EPIC #16)
* Products models can be modified to support Personalisation (of?) items

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Updated order flow design documented (LucidChart or similar) & added to Readme
- [x] Possibly designed as a multi-step checkout with personalisation as first step of checkout process

### Tasks

- [x] Task1 Discussed with shop owner to clarify requirments.  
* Would like to be able to immediately select ring size when a type 'ring' is selected.  Most rings are sizeable in H -> Q (ladies sizes) and H->S (mens sizes), but it varies with individual ring items (stones etc may affect sizing options)
* Some items are also suitable for engraving.  (This may be on an item-by-item basis as for example certain pendants, bangles or id bracelets are suitable for engraving.  The number of characters may also vary with the type of engraving.)  Note that rings are not engravable by this jeweller.
*  Please add the SKU onto the order line for ease of reference by the shop owner
- [x] Task2 The personalisation must be visible on the order confirmation, order history, and order admin view.
- [x] Task3 In products models - Add these fields to the Product model:  can_be_engraved (default False), max_char_engrave (default 0).  MIGRATE.  Also reduce SKU field to 20char.  Also add ring_size_min, ring_size_max.  Also develop StockType cat code (as wish to retire Cat6 values).  
- [x] Task4 products/models.py:  Add method has_sizes to Product, if cat_name="ring" then sizing is enabled.
- [] Task5 Update product-detail template (capture product_size (verified against a list ring_size options) , form (2 extra fields), view (to add logic for category ring -> pre-load extra fields and populate extra fields on saving) 
- [x] Task5 Basket doesn't have any models, it only has contexts.py to define the datastructures, and views to define how these are manipulated.  Update these (as per Boutique Ado - reinstate standard functionality) to deal with a sized product.   
- [x] Task6 basket - contexts for update and delete_basket - DONE
- [x] Task7 Add the following to the order detail - add fields OrderLineItem.sku , .product_size, .can_be_engraved, .engrave_text 
- [x] Task8 Update checkout template (product-detail form: SKU (write this in background), ringsize, personalisable, max-chars, personalisation

**Comment by DeeMcCart** [comment]
18/02/24  Ring sizing has been applied:  Based on cateegory of 'ring', a product method has_sizing is activated, and the product is treated differently through the add to basket - basket maniupation - checkout - order confirmation (checkout success) process.
Tested through add to basket (select ring size at that time), checked that different ring sizes generate separate basket lines.
Verified display on checkout screen.

ISSUES:
* No facility on checkout sceen to modify ring size - you would need to delete and re-add
* BUG:  Quantity increment and decrement in the basket removes the ring sizing.
