### ISSUE TITLE
User Story: FTU_19 Stripe Card Processing

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#21]
EPIC: #16 

FTU_19: As a **First-Time User** I want to **pay for my order using credit card** to **ensure the purchase is completed**

### Assumptions or Pre-Requisites:
* basket feature is in place #16
* checkout template is build #16 
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Card payment panel is populated so user can enter carc #20 
- [x] Must be able to perform a Stripe checkout using test card
- [x] Must receive order confirmation 

### Tasks

- [x] Task1 Build checkout portal
- [x] Task2 Integrate Stripe js
- [x] Task3 Test payments coming through to Stri

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
05/02/24 - this has been done to a basic level.  Stripe payments are now processing through using a test card.  


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/130b9014-115f-4d5a-96bd-905985b7fc3c)

**Comment by DeeMcCart** [comment]
06/02/24:  Follow-on task - Order total not saved to table #41
