### ISSUE TITLE
User Story: FTU_20 confirmation of order number

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#22]
EPIC:  #16 

* FTU_20: As a **First-Time User** I want to **receive an on-screen confirmation of order number** to **ensure the purchase is completed**

### Assumptions or Pre-Requisites:
* 'FIRST_ORDER_NUMBER' assigned in settings

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must increment order number based on max of existing order #s in table.  
- [x] If no order numbers in table, then use the value in the settings.

### Tasks

- [x] Task1 python subroutine to calculate max of order number in table and increment
- [x] Task2 Add to checkout views 

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
This is working as of 01/02/24

**Comment by DeeMcCart** [comment]
Emails extended 16/02/24 to actually send.  request 17/02 from shop owner/system owner that the shop email be copied as CC on email when na order is generated.  Have added parameter DEFAULT_CC_EMAIL to settings.py this will need to be set in test and PROD environments (if it is to be used).  Tested without setting the parameter ie blank CC email.
