### ISSUE TITLE
EPIC: Product Management

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#24]
**EPIC:**  

### Description:
This EPIC to capture all aspects of the 'Product' app from initial model creation through to having a template for sysadmin profile to edit and amend the products

Issues:
- [x] #28 View products and product detail **DONE**
- [x] #29 Product Lead times **DONE 14/02/24**
- [x] #30  Search for product by name or desription **DONE**
- [x] #31  Filter the products view **DONE 15/02/24**
- [x] #32  Sort the products view **DONE**
- [x] #33 View custom products
- [x] #66

**Comment by DeeMcCart** [comment]
DMcC Reviewed at end of Sprint 2 and noted which are 'Done'.
Product sorting - would like to also have ability to sort by newest products for RUs.  have added this #37 under epic #35 UX
