### ISSUE TITLE
User Story: FTU_27 Create User Profile 

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#26]
EPIC:  #1 

As a **user** I can **personalise my profile** so that **I can take advantage of greater site functionality**
(In fact there will be multiple user stories which depend on this particular task as a pre-requisite)

### Assumptions or Pre-Requisites:
*  EPIC #1 is underway
* Issue #3 has been done
* Issue #4 has been done (this takes care of the basic register-login-logout functionality)
* Issue #5 has completed the following tasks:
- [x] Create Profile app, models.py, views.py, urls.py, admin.py, profile.html
- [x] Build and apply Migrations
- [x] Verify the Profile data structure by adding in admin console.

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Profile personalisation page exists
- [ ] Includes newsletter signup checkbox (and current setting) - only if user has supplied email address
- [ ] Includes a section/link for wishlists (doesnt have to be an active section yet?)
- [ ] Includes a section/link for orders (doesnt have to be an active section yet?) with payment status and delivery status.
- [ ] Includes ability to upload profile avatar
- [ ] Avatar displays at top of page in navbar - success message Welcome XXXX

### Tasks

- [ ] Create user profile page
- [ ] Customise it with sections identified in acceptance criteria above
- [ ] Add avatar to navbar

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Reviewed 05/02/24:  Considerable work was done on this in Sprint1 - however there is an error 

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/86a3c7f9-4116-4ec2-a3d5-6c790f7f3b2b)

**Comment by DeeMcCart** [comment]
Sprint2 review - lots of issues with this so just moving it into Sprint3.  To resolve specific issues we have 2 tasks:
#39 
#40 

but there is still a lot to be completed on this user story according to the acceptance criteria above.

**Comment by DeeMcCart** [comment]
DMcC 17/02/24:  Just keep this for reference:  https://django-crispy-forms.readthedocs.io/en/latest/layouts.html
