### ISSUE TITLE
User Story: FTU_26 Authentication FTU_27 Create Profile FTU_03 Feedback

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#27]
EPIC:  #1 

FTU_26: As a **First-Time User** I would like to **signup for newsletter** to **increase my affinity with this retailer**
FTU_27: As a **First-Time User** I would like to **create a profile** to **track my history with this retailer**
FTU_03: As a **First-Time User** I want to **receive feedback** at each step on the site so that I **understand** what I am doing, and, if I'm in a multi-step process, I understand how far along I am in the processs

### Assumptions or Pre-Requisites:
* Base repo has been configured
* AllAuth has been installed
* Many Individual user stories rely on signin/ signout/ authentication/ profile functionality
* User can register successfuly
* User is required to enter an appropriate password configuration (min length, etc)
* User receives appropriate notifications of problems with registration password (doesn't meet criteria, 2 passwords don't match etc)

### Acceptance Criteria: (Must be completed before task is moved to 'Done')

- [ ] Preference is that an email is NOT mandatory for profile creation (later on, will be required to give an email if want to create an online order)
- [x] If a user does supply an email address on registration, they should be offered a checkbox 'send newsletter'.  This checkbox should supply an appropriate popup alerting the user to privacy policy (and anything else required by GDPR)
- [x] User can sign in after creating a profile
- [x] If a user is attempting to signin and enters incorrect credentials then appropriate action should be taken....

### Tasks
- [x] Extend Allauth using a custom form to capture additional fields
- [x] At time of creating a 'User', also create a 'User Profile'
- [x] Connected to Toast messaging to provide feedback to user

**Comment by DeeMcCart** [comment]
worked on this 29/01/24 and 30/01/24 - getting deeper into the mire.  Working within profiles app, but have become very confused with the connection between views forms templates.  At this point I can:
* create user & user profile using an extended allauth registration form.  
* Fields are successfully loaded into the allauth 'user' record (firstname, lastname & email address) 
* UserProfile form fields are validated at time of entry
_* However, it throws an error 'WSGIRequest' object has no attribute 'errors' from allauth.account.views.SignupView_

* Profile image is now displayed on top navbar (within template navbar-profile.html)

* Attempting to get user profile template to display however got very snarled in forms - views - tempates, so committed and will walk away from this for a while.  Getting as far as error on one of the fields......

**Comment by DeeMcCart** [comment]
DMcC 05/02/24 Closing out this user story based on the tasks defined, and splitting out the remaining items to put in the backlog for Sprint 3.

 as, even though some of this work done (e.g. profile image display based on maintaining via admin console), this needs a fresh look.  Note that the newsletter signup is available within integrated user-user profile creation 

**User sign-in & signout are successful and show Toast Messsages:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/1bdada96-2488-4185-a2f1-95506f29cc1b)

**User registration includes User and UserProfile setup and includes newsletter checkbox**


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/ba3536e7-445d-438c-9fc8-d0b3a374a46b)

However getting an error when user goes to register:


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/623cfca1-fdd8-41c6-a151-ecc0976938e2)

**Comment by DeeMcCart** [comment]
End of Sprint2 review - closing out this user story for Sprint 2.  New tasks created for Sprint3:
Task # 39
Task #40
