### ISSUE TITLE
User Story: FTU_06: View a range of products with product characteristics

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#28]
EPIC:  #24 

* FTU_06:  As a **First-Time User** I want to **see a range of products which are offered by the Jeweller, to see pictures, descriptions price (for off-the-shelf items), lead-time for each item** so that I can **make purchase decisions**

### Assumptions or Pre-Requisites:
* Products app is installed

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to navigate to Products page and see overview
- [x] Must be able to navigate to Product Detail page and see a fuller product description

### Tasks

- [x] Task1 Install Products app
- [x] Task2 Models Admin Views Templates 
- [x] Task3 urls for product product detail 
- [x] Task4 Amend menu links to access products
- [x] Task5 Add product categories to reflect item type, metal type, stones, colours, lead times, suppliers
- [x] Task6 Install & Configure templates for Product, Product Detail

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Worked on this 30&31/01/24; now have a reasonable approach:

**All products:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/a4d4a2a4-8ea2-4341-85ee-6017bc685b75)

**Product detail:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/3772455f-e8f8-43dc-8c8f-f1b6608dde7c)

**Product category filters (based on category data loaded 30-31/01/24):**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/6f7b18e4-264b-411a-99d7-67e8a897511d)

**Comment by DeeMcCart** [comment]
Just realised **lead time** not yet displaying.... this is stored in cat5.  
Also filter on stones (which an be found in cat 3 OR cat4) not yet working fully.
A little bit more work to do on this before completed....
