### ISSUE TITLE
User Story: FTU_07 Product lead times

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#29]
EPIC:  #24 

FTU_07:  As a **First-Time User** I want to understand **whether an item is in-stock, made-to-order** and **what are lead times (e.g. available now, lead time 6 weeks for make-to-order, lead time 1 week for casted items)**

### Assumptions or Pre-Requisites:
* Issue #28  completed
* Categories setup for products

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Lead time is clearly visible per product
- [x] (Ideally lead time will default from product category and can be set per individual product)

### Tasks

- [x] Task1 Define a structure for representing lead time wiithin the Products app
- [x] Task2 Define a structure for defaulting from Category
- [x] Task3 Define a structure for maintaining lead time per Product
- [x] Task4 Add to product detail template, so that customer can make an informed buying decision
- [x] Task5 Add field planned_ship_date to the Order model
- [x] Task6 Calculate planned_ship_date at time of order confirmation, and store on the order
- [x] Task7 Inform user in order confirmation email of expected ship date based on the product leadtime

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
31/01/24:  DMcC: Now represented in the Product model, as cat 5 (?).  

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/4e8c6979-0ec0-4ac7-98e1-7d2eed9412cb)



with these values selectable on a product:


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/4787a8e1-e5c5-4f49-8cb1-b4df086c209b)

**Comment by DeeMcCart** [comment]
14/02/24 DMcC:  Returned to this and simplified the structrue.  lead time(days) now represented by an integer field on the product, if this is 0 then the lead time is taken from the product's cat6 (STOCK, MTO, COMM etc) value, as these each have different lead times.  The products model now includes:

def lead_time(self):
        """ return lead time for product, if not set """ 
        """ on product use from category leadtime """
        if self.item_lead_time != 0:
            return (self.item_lead_time)    
        else:
            return (self.cat6_value.default_lead_time)

This is seen on the product detail as per images below:



![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/d88d8ef0-8e30-4c8a-9202-1d25c1042d64)
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/c03b1782-dcdb-4a6b-b98a-b440af6340ce)
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/e008b033-6211-44c3-ab89-3bb5f0c4f058)
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/2fa9d672-83b5-4094-aefb-161ff0844d9f)
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/8d58f6ba-4dd7-418d-92fc-6aaf55e4886d)

**Comment by DeeMcCart** [comment]
14/02/24 DMcC
added field order.planned_ship_date, method order order_ship_date (based on latest date of any order lines)
added field orderline.line_ship_date, method item_ship_date 
Methods are not available to the order at first creation (werent picking up as default values) but can be used within the order creation functions.   Job done.
