### ISSUE TITLE
User Story: FTU_08 Search for product by name or desription

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#30]
EPIC:  #24 

* FTU_08:  As a **First-Time User** I want to **search for a product by name or description** to **know if Jeweller sells the item of interest**
 
### Assumptions or Pre-Requisites:
* Products models etc in place

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to search for a particular product (or part of product name)
- [x] Must be able to search for part of a product description

### Tasks

- [x] Task1 Implement Products html & associated js to allow for search functionality
- [x] Task2 Test it

**Comment by DeeMcCart** [comment]
DMcC 05/02/24:  Updated post Sprint2.  This was built during Sprint2 as part of the Products functionality.  Feature illustrated here:

Search by part or all of product name:
![image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/5212c1bc-4d6e-4e9a-a8dc-f09ee9724940)

Search by part of product description:


![f98-search-by-description-p1](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/203c0cc1-045b-40f7-be0c-c317f18a376f)


Search by product description:


![image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/2e8b06cd-d95b-4e34-85c5-806cc77e8bb3)
