### ISSUE TITLE
User Story: FTU_09, SO_08 Filter the product view by (configurable) categories

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#31]
EPIC:  #24 #34 

FTU09: As a **First-Time User** I want to **filter my product view** to **see only what I'm interested in ** (e.g. particular metals, stones, colours, particular occasions) (Preferably filter by multiple categories)
SO_08 As **System Owner** I want to **create and maintain product categories** to **assist in sorting and filtering for users**

### Assumptions or Pre-Requisites:
* Product app is setup and products are populated with data
* Categories have been setup and populated with data 

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Would like to be able to show/offer on sysadmin-defined category names
- [x] Must be able to filter on sysadmin-defined category values e.g. item type, metal, stone, colour, etc 
- [x] Need a sysadmin maintenance page to allow editing and setting of these categories

### Tasks

- [x] Task1 Models,, admin, forms, views
- [x] Task2 Modify the main page header to accomodate customisable filters
- [x] Task3 Build templates for maintenance

**Comment by DeeMcCart** [comment]
31/01/24 - working on Product & Category models to fulfill pre-requisites - kind of understand better whats needed by populating with data and tweaking the structures to better meet this requirement.
Need to work on the Views because we need a function that returns a list of categories which should be displayed.  these then need to be used for filtering so need to e used to build a parameter string.
