### ISSUE TITLE
User Story: FTU_01, FTU_03, SO_01 Clear understanding of site purpose/ feedback

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#36]
EPIC:  #35 

* FTU_01  As a **First-Time User** I want to **quickly understand the site purpose** so I **can decide whether to spend time exploring and discovering the site**
* SO_01 As **System Owner** I want to **provide a system that is easy to use** to **encourage users to visit and return to the site**
* FTU_03 As a **First-Time User** I want to **receive feedback at each step on the site** so that I **understand what I am doing, and, if I'm in a multi-step process, I understand how far along I am in the processs**

### Assumptions or Pre-Requisites:
* To be verified at initial deployment, MVP deployment and Final version deployment

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have purposeful landing page
- [x] Must have cleara CTA (call to action)
- [ ] Understand that site s for a particular jeweller, where the jeweller is located, what services are offered, and what the limits of service (e.g. geographical) are 

### Tasks

- [x] Task1 Build site
- [x] Task2 Review and resolve errors
- [x] Task3 User feedback messages at each stage
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
01/02/24 Apparance:  removed filter on products page, was set to 0.7 grayscale and dulled down the jewellery photos a bit, thi was noticed by the shop owner who asked they be nice and bright and shiny - done, removed filter.

**Comment by DeeMcCart** [comment]
18/02/24 Feedback from end-user testing and site validation - can the logo show the jeweller location on evry page ie Jewellers Carlow' - will do that quikly during Sprint5
