### ISSUE TITLE
Task: Sprint 2 Retrospective, Sprint 3 Planning

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#38]
EPIC:  #10 

As a **scrum master/developer** I can **follow Agile principles** so that **project functionality is achieved incrementally across sprints**

### Assumptions or Pre-Requisites:
* Agile methodology is being followed for this project
* Closing out (weekly) sprint should be done with a retrospective
* Planning of next sprint should be done with backlog grooming and deciding which tasks to move to 'to do' for this sprint
* Respect timeboxing and not try to complete any tiny outstanding items from previous Sprint 'quickly' in the new Sprint. The time has passed so now deal with any hangover items in CURRENT sprint

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
* Sprint2 closed off (this happens automatically when using iterations)
* Any issues which were linked to Sprint2 but not in 'Done' status reviewed and
moved to next sprint for completion of outstanding tasks
* OR if the acceptance criteria is met and tasks done, but there are issues, then log the issues as a bug and closeout the original UserStory/ task

### Tasks

- [x] Task1 Retrospective
- [x] Task2 Backlog groominig
- [x] Task3 Sprint Planning and issue prioritisation
- [x] Task4 Update readme with work to date

**Comment by DeeMcCart** [comment]
Mon 05/02/24:  Having a bit of difficulty reviewing the Sprint as a lot of work was done in Sprint 2 (Products, including Product Search & Filter, Basket, Checkout, Stripe).  Each is working at a basic level now but there are issues which need to be resolved and sub-features which needs to be split out into separate user stories for a round 2 approach.

Note that there are some code elements that will need re-factoring, e.g.:
* the Stripe js wasn't picking up (getting a 404 on the .js file), so has been incorporated as a <script> element directly in checkout.html;
* + and - buttons not working on the product detail screen when adding to basket - something related to picking up the js (again);
* + and - are however working OK on checkout screen;
* user profile screen not loading and throwing an error possibly related to version of allauth
* order total being loaded to file as 0, even through order validates through Stripe correctly
* System owner statement that sizing is essential for rings.
* New background image provided by system owner, this is visible in dev environment but not yet visible on tablet screen (possibly as we're not sure how to do a hard refresh on the tablet screen).

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/cfba2bc9-73df-4503-8bdb-056cb977adc4)

**Comment by DeeMcCart** [comment]
06/02/24:  Updated Readme with some references, user story#s, started on features (1 hr) .  Closing off this task now.
