### ISSUE TITLE
Task:  Resolve issues with User Profile Registration

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#39]
EPIC:  #6 
FTU_26: As a **First-Time User** I would like to **signup for newsletter** to **increase my affinity with this retailer**
FTU_27: As a **First-Time User** I would like to **create a profile** to **track my history with this retailer**

### Assumptions or Pre-Requisites:
*  Allauth has been setup
*  Extended signup has been installed, but is not working correctly

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] User Must be able to complete registration (currently getting error)
- [ ] User **should** be allowed to signup without mandatory email registration (as many of the existing customers use mobile phone as primary point of contact)
- [x] User should receive appropriate Toast messages at each point of the signup process

### Tasks

- [x] Task1 Issue investigation & resolution for registration error
- [x] Task2 Investigate whether its possible/advisble to allow signup without providing an email address **NOPE:  system depends on being able to generate emails and actually its probably a better design to enforce the email-confirmation process**
- [x] Task3 Check appropriate display of Toast messages
- [ ] Add account email verification on signup.... based on implementation decision that emails are needed.

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
DMcC 19/02/24 Sprint4 Review:  Closing off this issue as have tried various approaches and concluded that, for this app, it is best if emails are mandatory.
