### ISSUE TITLE
Task:  Setup Authentication

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#4]
EPIC:  #1 

As a **user** I can **register -signin - sign in-out** so that **I can operate with a user profile**

### Assumptions or Pre-Requisites:
* Base repo has been configured
* AllAuth has been installed
(Assumption:  there will be separate user stories specifically relating to how this functionality is applied/used by the various roles, however all rely on this initial setup as a core 

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] User can register successfuly
- [x] User is required to enter an appropriate password configuration (min length, etc)
- [x] User receives appropriate notifications of problems with registration password (doesn't meet criteria, 2 passwords don't match etc)
- [ ] Preference is that an email is NOT mandatory for profile creation (later on, will be required to give an email if want to create an online order)
- [ ] If a user does supply an email address on registration, they should be offered a checkbox 'send newsletter'.  This checkbox should supply an appropriate popup alerting the user to privacy policy (and anything else required by GDPR)
- [ ] User can sign in after creating a profile
- [ ] If a user is attempting to signin and enters incorrect credentials then appropriate action should be taken....

### Tasks
- [x] Install AllAuth
- [x] Add options to navbar
- [x] Amend/update the Allauth screens so they have a consistent look and feel
- [ ] Ensure connected to Toast messaging

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
26/01/24:  Installed & uninstalled several times as wanted to install crispy_bootstrap5; this incremented the installed Python from 3.9.7 to 4.2.9; and allauth failed on handshake... conclusion after a bit of back-and-forth was to accept later installation versions.  Some rework on each re/install.  However now have a reasonably good look and feel.
re Daisy McGurr (?) Utube Django series.  Resulting styled allauth forms below.  The remaining forms could do with a bit more work, and I'd like to resequence some of the fields (e.g. registration requires password to be entered twice which is a total waste, also would like people to be able to enter their phone# at this point if at all possible)

**Comment by DeeMcCart** [comment]
**allauth registration template:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/4d703241-7322-4763-b8ef-6aa0c4306e81)

**allauth login template:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/4d80ab51-9c23-4c23-a355-c91b4c23d289)

**allauth llogout template:**

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/86d780d8-1ff8-47c7-8202-0d0c37f9587c)

**Comment by DeeMcCart** [comment]
**Validation of username length:**



![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/a543eb80-0f0a-4ace-b010-73b98dd1da72)

**Validation of password:**



![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/9051aa0a-8f3c-4a02-80a0-043925e72112)

**Comment by DeeMcCart** [comment]
**Newsletter signup: (not working exactly as expected):** <- shouldnt be mandatory ie user doesnt need to check this box to continue


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/29fe30ea-2550-452f-a6fd-13e34ebf120c)

**Comment by DeeMcCart** [comment]
Closing out this Sprint1 issue with marked items completed; create separate Sprint2 issue for the outstanding items
