### ISSUE TITLE
Task: Resolve Isues with / Enhance User Profile page

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#40]
EPIC:  #6 

FTU_27: As a **First-Time User** I would like to **create a profile** to **track my history with this retailer**
RU_XX: As a **Returning User** I would like to **view my profile** to **view my ordering history with this retailer**

### Assumptions or Pre-Requisites:
* Basic all auth and profile work has been done, but errors on reaching user profile page

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have a functional user profile page
- [ ] Must be able to maintain profile image
- [x] User profile page should show previous order history

### Tasks

- [x] Task1 Investigate error 'UserProfile has no attribute headers'
- [x] Task2 Compare user profile page to boutique Ado walkthrough created
- [x] Task3 Re-use modified BA views and template codes.
- [x] Task4 Test

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
OK now testing (after some small edits to settings.py new user registration).  Get this error on pressing enter on the registration form:


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/475880dc-b0ab-4a66-879c-975cc45284ad)

**Comment by DeeMcCart** [comment]
OK reviewed this module and profiles page now working (close to)correctly:
Still needs ability to update profile image.


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/72346f31-320d-4908-8058-6b4cd79e77f7)

**Comment by DeeMcCart** [comment]
Raised #45 to deal with profile pic bug
