### ISSUE TITLE
User Story:  FTU_18 Personalisation (Engraving)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#43]
EPIC:  #48 

FTU_18: As a **First-Time User** I want to **personalise my order** to **reflect gift messages, special wrapping etc**

### Assumptions or Pre-Requisites:
* Basic Order flow is established and functional (EPIC #16)
* Ring sizing has been implemented
* Fields already added to Product model:  can_be_engraved (default False), max_char_engrave (default 0).
* Field already added to OrderDetail model: engrave_text
* Looking more closely at the Model structure, it seems engraving will need to be captured at the basket stage, as the order line is not saved until AFTER the order is created & paid for (its a bit late then to be asking the customer if they'd like some personalisation).
* Assumption:  Sizing and engraving are mutually exclusive, as per requirements clarification by Jeweller below.

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Engraving/ personalisation offered at time of adding to basket for products with can_be_engraved=True

### Tasks

- [x] Task1 Discussed with shop owner to clarify requirments.  
* Some items are also suitable for engraving.  (This may be on an item-by-item basis as for example certain pendants, bangles or id bracelets are suitable for engraving.  The number of characters may also vary with the type of engraving.)  Note that rings are not engravable by this jeweller.  can_be_engraved should be set on the product.
- [x] Task2 Must be available as an input field for engraveable items when adding item to basket (product_detail.html)
- [x] Task3 Make visible in the basket review screen? (basket.html)
- [x] Task4 Make /selectable/editable in the basket adjust
- [x] Task4 Make visible on the checkout screen (checkout.html)
- [x] Task5 Carry through to order line creation (both in checkout/views and in webhooks)
- [x] Task6 Make visible on the order confirmation email, order history (checkout_success.html), and order admin (order_maint.html)view.

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
NOTE:  Implemented as a secondary data structure for the t=uitem {engrave_test: engrave-text, qty} similar to the sizing data structure


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/99249b37-c322-4c8b-9d35-449b2ce18d74)
