### ISSUE TITLE
Task:/ Issue:  User Profile - profile picture not updating

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#45]
EPIC:  #6 

* RU_02 As **Returning User** I want to **add an image of my choosing to my profile** to **personalise my experience**
* Amend user profile - profile pic not updating

### Assumptions or Pre-Requisites:
* Profile page working in general
* Other updates being processed.

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to upload new profile pic
- [x] Must be able to press Update and get message profile updated successfully, profile image saved must update

### Tasks

- [x] Task1 Investigate and resolve
Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Ref:  https://www.youtube.com/watch?v=_P_-gum7rio codemy.com 'Uploading a user profile picture'

**Comment by DeeMcCart** [comment]
**Profile page with image:**



![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/ce1f777e-cf4d-483b-8e04-bd8c762b925e)


**Change the image file and click on Update Information:**



![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/93239c07-af84-46af-8f61-602dac1ebf84)

**Confirmation the image has updated:**


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/83d77b80-2d93-4d17-8a11-fa69b63d62c6)

**Comment by DeeMcCart** [comment]
DMcC 09/02/24 - improved UX using CustomClearableFileInput django widget: 


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/7bb3b1ce-bdf0-4c70-a2d0-42c739217a5b)
