### ISSUE TITLE
User Story: Robust Stripe Payments

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#47]
EPIC:  #16 

SO_14 As **System Owner** I want to **provide a robust payment interface** so as to **maintain trust and integrity and minimse payment queries**  

### Assumptions or Pre-Requisites:
* Stripe has been installed and is working as part of the checkout process

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must capture payment intent as incomplete payment at time of checkout screen load, this should be visible in Stripe as an incomplete payment but with the correct total
- [ ] Must capture updated total if any detail is changed on the checkout screen (? is it possible to change details at this point without returning to basket?)
- [ ] Deal with the situtation where a user closes the browser window after the payment is confirmed but before the checkout form is submitted (potentially end up with a payment in Stripe but no order associated with it, ie customer is charged but doesnt receive goods

### Tasks
- [x] Task1 Build Stripe webhooks (these will send signals from Stripe to a URL we specify)
- [x] Task2 Update settings.py
- [x] Task3 Update env.py with STRIPE_PULIC_SECRET, STRIPE_PRIVATE_SECRET
- [x] Task4 Build Stripe endpoint for development site https://8000-deemccart-cipp5jeweller-10k3i9z0k0t.ws-eu108.gitpod.io/checkout/wh/.  Enable all services.  Reveal WH secret.
- [x] Task5 (Stripe Part 11) Update env.py with STRIPE_WH_SECRET  & restart server
- [x] Task6 (Stripe Part 12) Update stripe-elements.js to transfer billing and shipping addresses (currently assumed to be the same) to the payments form
- [x] Task7 (Stripe Part 13) Add checkout/views.py metadata view to transmit data re user-save-delivery-address option (& possibly other options such as order #)
- [x] Task8 (Stripe Part 14) Create a URL whereby Stripe can be sent (?) the cached data: path('cache_checkout_data/', views.cache_checkout_data, name='cache_checkout_data').  Test to prove can pass information from custom form to Stripe via the payment intent & recapture on webhook so that we can re-use it.
- [x] Task9 (Stripe Part 15) Check the order details to see if it has been created successfully in the database (as we expect it to be), giving it enough time (Stripe part 16) for asynchronous loading,  then creating the order if not already found.
- [x] Task10 (Stripe part 16) Add fields original_basket, stripe_pid as further unique identifiers to the order model (migrate etc), include these in admin.py as readonly_fields & fields.  Add hidden input field in payment section of checkout form:  <input type="hidden" value="{{ client_secret }}" name="client_secret">.. do something else in checkout and something else in views.  Finally in webhook_handler include the fields (original_basket=basket, stripe_pid=pid) when trying to find the order, and then when creating the order if not found on the database.
- [x] Task11 (Stripe part 17) - TEST for errors/crashes in app (check for direct crash, then terminal console for errors).  Check Stripe - main dashboard - webhooks - should see success rate here.

**Comment by DeeMcCart** [comment]
DONE 06/02/24 - now I'm not entirely sure how you would check if the webhooks kick in to create the order when needed.... might need to either look at automated testing (that would be new to me) or to force a failure situation by pressing the checkout button and then immediately killing off the session.......
**This is the view from Stripe, within the endpoint:**


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/7159f38f-e15e-4666-b1d8-ad001350cd28)
