### ISSUE TITLE
User Story: SO_08, SO_09, SO_10 System Admin - Products

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#49]
EPIC: #34 

* SO_08 As **System Owner** I want to **create and maintain product categories** to **assist in sorting and filtering for users**
* SO_09 As **System Owner** I want to **create and maintain products** to **administer the site and keep it current**
* SO_10 As **System Owner** I want to **identify make-to-order/custom products as well as off-the-shelf** products to **advertise both business streams**

### Assumptions or Pre-Requisites:
* Core part of system is constructed with Products app installed and base functionality working #1 

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] (System admin only) must be able to add products via a front-end screen
- [x] (System admin only) must be able to edit products via a front-end screen

### Tasks
- [x] ADD PRODUCT:
- [x] Task1 products/forms.py
- [x] Task2 products/views.py def add_product(request)
- [x] Task3 products/urls.py path('add/', view.add_product, name='add_product')
- [x] Task4 add_product.html
- [x] Task5 TEST add product
- [x] EDIT PRODUCT:
- [x] Task6  products/views.py def edit_product(request)
- [x] Task7  products/templates/product/ edit_product.html
- [x] Task8 URLs.py  path('edit/<int:product_id>/', views.edit_product, name='edit_product')
- [x] Task9 URLS.py path('delete/<int:product_id>/', views.delete_product, name='delete_product')
- [x] DELETE PRODUCT: 
- [x] Task10 products/views.py def delete_product(request)
- [x] Task11  includes/nav-profile.html dropdown to <a href="{% url 'add_product' %}" class="dropdown-item">
- [x] Task12 Add edit and delete links in appropriate places (where the product id is known) ie product card 
{% if request.user.is_superuser %}
     <small class="ml-3">   <a href="{% url 'edit_product' product.id %}">Edit</a>
     <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a> </small> {% endif %}
- [x] APPLY SECURITY:
- [x] Task 13 Protect the URLs for edit and delete so that these cant be accessed directly by someone other than sysadmin.  Also check within each function that the currently logged in user is a superuser, otherwise return them to the home page.
- [x] IMPROVE IMAGE FILE UX: 
- [x] Task14 (Ref 'Fixing the Image Field - Part 1')  To cleanup display of product images in the add/edit/delete screen (because they do look truly shite) Create a file Products/widgets.py and import some widgets and lazy text handler.  This refers to a template Products/custom_widget_templates/custom_clearable_file_input.html.  ...... EVENTUAL SUCCESS WHEN FORM FIELDS DISPLAYED INDIVIDUALLY
- [x] Task15 Add content to this, and on the Products/forms.py refer to the template for the image in class ProductForm.
- [ ] Task 16 TEST

**Comment by DeeMcCart** [comment]
DMcC 08/02/24 Need to revert to the 'Fixing the Image field lessons Part 1/2' as this holds the solution for visibility of images on Product add/ **but more particularly on Product Edit**.

Would really like to enhance this by offering a grid view for product add/edit/delete. 
Would also like to enhance this by offering a delete confirmation message, as it is quite scary that a product could inadvertently be removed from the database (and it would be hard to recreate it and see it, for example, on existing orders)

**Comment by DeeMcCart** [comment]
Tested through end-to-end and works fine but could do with some refinement (in Sprint 4):
Added task  under UX to tidy up:
- Confirm delete message
- deal with the situation where the product is deleted and the historical order is displayed (currently the item description disappears/shows blank and the order total shows 0)

(Note that this will also deal with the situation where an item price is updated as otherwise that would update all previous orders to the new price)
