### ISSUE TITLE
Task: Create json extract from DEV load into PROD database

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#51]
EPIC:  #7

As a **role** I can **capability** so that **received benefit**
As a **role** I want to **action** to achieve **desired outcome**  

### Assumptions or Pre-Requisites:
* First Deploy & MVP deploy done

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must have DEV database populated
- [ ] Must have PROD database created with same structure as DEV

### Tasks
- [ ] Make sure you are connected to the local Sqlite3 database in Gitpod
- [ ] Make a backup of the app's data that you want. For the example, we will use the "product" app.  (type this command, do not copy and paste):  **python3 manage.py dumpdata products > products.json**
- [ ] Make sure you are connected to the online Postgres database in Heroku.
- [ ] Transfer the backup json file data that you just created.  (type this command, do not copy and paste):  **python3 manage.py loaddata products.json**
- [ ] Repeat for any other apps you wish to transfer.

**Comment by DeeMcCart** [comment]
Incorporated into issue #9, closing this out
