### ISSUE TITLE
User Story: FTU_03, SO_01: Consistent Feedback to user (Messaging-Toasts)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#53]
EPIC:  #35

FTU_03 As a **First-Time User** I want to **receive feedback at each step on the site** so that I **understand what I am doing, and, if I'm in a multi-step process, I understand how far along I am in the processs**  
* SO_01 As **System Owner** I want to **provide consistent user feedback** to **assist users in navigating the site**

### Assumptions or Pre-Requisites:
* Base site is constructed
* Messages are in place within individual apps just not 100% consistent

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must have appropriate messages at each stage of CRUD processes (read a record, edit a record, update a record, add a record, delete a record)
- [x] Messages must be consistent across apps

### Tasks

- [x] Task1 Review messages and build databank of messages and when they should occur
- [x] Task2 Distinguish between restricted-security messages and process-related messages
- [x] Task3 When a user reviews a historial order would prefer them not to see a toast message if order status is PACKED SHIPPED RECEIVED (DONE - just changed the wording of toast message for historical vs newly-created orders)

**Comment by DeeMcCart** [comment]
14/02/24 DMcC:  Added timeout to Toast messages as follows - assigned id msg, added script below:
  
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 5000);
    </script>
