### ISSUE TITLE
Task: Sprint 3 Retrospective, Sprint 4 Planning

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#54]
EPIC:  #10 

As a **scrum master/developer** I can **follow Agile principles** so that **project functionality is achieved incrementally across sprints**

### Assumptions or Pre-Requisites:
* Agile methodology is being followed for this project
* Closing out (weekly) sprint should be done with a retrospective
* Planning of next sprint should be done with backlog grooming and deciding which tasks to move to 'to do' for this sprint
* Respect timeboxing and not try to complete any tiny outstanding items from previous Sprint 'quickly' in the new Sprint. The time has passed so now deal with any hangover items in CURRENT sprint

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
* Sprint3 closed off (this happens automatically when using iterations)
* Any issues which were linked to Sprint3 but not in 'Done' status reviewed and
moved to next sprint for completion of outstanding tasks
* OR if the acceptance criteria is met and tasks done, but there are issues, then log the issues as a bug and closeout the original UserStory/ task

### Tasks

- [ ] Task1 Retrospective
- [ ] Task2 Backlog groominig
- [ ] Task3 Sprint Planning and issue prioritisation
- [ ] Task4 Update readme with work to date

**Comment by DeeMcCart** [comment]
**DMcC 12/02/24:  Task1 Retrospective:** 

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/887faeb9-335b-4407-84c3-1ed690ffffaa)

**Comment by DeeMcCart** [comment]
**Task3 - Sprint Planning & Issue Prioritisation**
Focus on:
Redo deploy so that static and media files operate correctly
Add remaining custom functionality (reviews and feedback form)
Get additional addresses functionality working
Apply consistent looks & feel (particularly too AllAuth forms)
