### ISSUE TITLE
Task: Tidy-up Product delete

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#55]
EPIC:  #35 

As a **role** I can **capability** so that **received benefit**
As a **role** I want to **action** to achieve **desired outcome**  

### Assumptions or Pre-Requisites:
* Product CRUD installed & working
* Delete function works but doesnt display a confirmation message
* Delete function works, but historical orders don't display correctly (total price calculates to zero)

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must show delete confirm message when Product is deleted
- [x] Must be able to view historical orders with correct price detail and description (even if the product no longer exists)
- [x] Consider adding a 'hide from display' flag 

### Tasks
- [x] Task1 Added delete confirm message
- [x] Task2 Added 'hide display' button to product model & made it maintainable
- [x] Task3 Looked at signal-receiver order-update to see if the order total update could be prevented if order is in SHIPPED or RECEIVED STATUS
- [x] Task4 Final solution - prevented delete if the product exists on an order, direct user towards 'maint' instead.

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
On consideration, it would be better if products that are already on orders could be prevented from deletion.   Perhaps a warning to the user of the order numbers that exists and a suggestion to hide the product from display instead?
