### ISSUE TITLE
Task: Tidy-UP MVP Deployment

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#56]
EPIC:  #7 

As a **system owner** I can **deploy and re-deploy the system with MVP functionality** so that **the site operates as expected with MVP functionality**

### Assumptions or Pre-Requisites:
* Deployment has been created for MVP, but some issues with static files and media files not being picked up in collectstatic process and not being displayed on screen, or throwing errors on display.
* The current deployment process takes 10-15 minutes and seems to be collecting images (rturns a message to say 163 files collected) but its not clear where/why it is storing them
* Possibly related to Amazon S3 bucket in different time zone (Sweden not Ireland)

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to operate deployed PROD site as per DEV site
- [x] Deployment process must be repeatable, possibly with auto rebuilds on commit

### Tasks 
- [x] Task1: Re-deploy to Heroku & monitor build time (5 mins) 
- [x] Task2: Check re static files (YES these were updated during the deployment)
- [x] Task3: Check re error messages or differences in environment (One seen, related to commentd-out python code still being picked up from the nav-profile.html template - removed the commented-out code)
- [x] Task4: Re-migrate the database structures
- [x] Task5: Dump products, home to json and load into PROD (worked OK for home but not for products, as these have dependencies on certain users for rviews etc - manually set up the PROD data in alignment with DEV)
- [x] Task6:  Setup Stripe endpoint for PROD server
- [x] Task7:  Test (some strange behaviour with duplicate orders created within the PROD database, however these only have been sent to Stripe once - can investigate later.  Also some strange behaviour on checkout screeen where it doesnt seem to be interacting with the UserProfile object)
- [x] Task8:  Configure email processing to happen from PROD sent from allskills address

**Comment by DeeMcCart** [comment]
16/02/24:  Got to the bottom of some of the issues:
* commented-out code was causing an error related to teh user profile images on navbar.  Removed the commented-out code

**Comment by DeeMcCart** [comment]
![image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/135f5819-d75e-4b85-be2e-ff3a1512b951)
