### ISSUE TITLE
User Story: RU_13 Leave Reviews

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#57]
EPIC:  <epic>

* RU_13 As a **Returning User** I would like to **create Product Reviews and ratings** to **increase interaction with the site and help to guide other purchasers**

### Assumptions or Pre-Requisites:
* Core functionality is up and running including Product and Product Detail views
* Product model includes an average review

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] (Registered users) Must be able to leave a product review 
- [ ] Preferably if they have purchased the item in question?
- [ ] Reviews can be moderated and approved by the site administrator

### Tasks

- [x] Task1 Extend Product Models to include reviews (already in place)
- [x] Task2 Extend Product App to include Reviews entry form per product
- [ ] Task3 Extend email confirmation to include a suggestion that the customer leaves a review
- [ ] Task4 Add a review form where a registered customer can leave a review for a product they have purchased ('review' button appears beside any product they have purchased
- [ ] Task5 Add a panel for sysadmin to view comments and approve them??  (Might not be necessary)

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
DMcC 13/02/24:  Partly done, the review display looks OK just need to add a proper review entry and save capability R done CRD needed.
