### ISSUE TITLE
User Story: SO_06, RU_06 View & Monitor Order status

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#58]
EPIC:  #48 #34 

* SO_06 As **System Owner** I want to **track orders raised** to **ensure they progress through the shipping lifecycle**
* SO_07 As **System Owner** I want to **link to an post tracking** to **provide delivery status to customers**
* RU_06 As a **Returning User** I want to **view my order status** so I **know if the order has been shipped**

### Assumptions or Pre-Requisites:
* Base site is up & running with checkout etc
* Order follows a logical status flow - ORDERED - PACKED - SHIPPED - RECEIVED

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] SysAdmin must have visibility on orders raised and their status
- [x] User can see order status, delivery method and planned ship date on order confirmation & email
- [ ] SysAdmin must be able to update status as needed
- [x] Customer must receive email notification on reaching 'ORDERED' status
- [ ] Would be nice if customer could receive email notification when order moves to 'PACKED' status
- [ ] Would be nice if customer could receive email notification when order moves to 'SHIPPED' status

### Tasks
- [x] Task1 Add 'status' field to order model
- [x] Task2 Make status (& delviery method, planned ship/collection date visible on order confirmation.
- [x] Task2 Build a sysadmin console for order view & edit
- [ ] Task3 Add customer email creation when ordr moves to 'PACKED' status
- [ ] Task4 Addd customer email creation when order moves to 'SHIPPED' status

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
DMcC 15/02/24 have the sysadmin order maintenance console with 'view' mode working fine (can drill into order history).  Only problem is that the order history returns the user to the user profile rather than where they came from ie maintenance.
Also I have a modal to move the status along for an order but it is not connected to anything yet, this needs more work.... screenprints below to illustrate


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/85199bd9-be2b-41dc-b526-43473404e2e1)
![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/3cc0451f-35ff-4a08-9526-a9c6cbfe54ec)

**Comment by DeeMcCart** [comment]
16/02/24 14:30 - Email confirmation on ordering now received; have built shipping_email_subject and _body templates, need to apply these next
