### ISSUE TITLE
EPIC: User Authentication and User Profile

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#6]
**EPIC:**  Setup/Customise User Authentication & User Profile

### Assumptions:
Allauth already installed in EPIC #1 
Toasts already setup for display in EPIC #1 
Email sending not yet setup

### Acceptance Criteria:
Standard Look & Feel across register/login/out screens

### Description/ Key tasks:
- [x] #4 Configure register, signin, signout, password reminder functionality
- [x] #5 Add a profile page Sprint1
- [ ] #26 Create User Profile (Sprint2 remaining items from issue #5 )
- [x] #45 Allow user to edit their Avatar (Sprint3)
- [ ] #39 Resolve issues with User profile registration
- [x] Use CustomClearableFileInput widget to improve UX on profile image
- [ ] Allow user to edit their firstname & lastname
- [ ] Allow user to edit their delivery/ billing address
- [x] Send email notifications

**Comment by DeeMcCart** [comment]
USER PROFILE EMAILS - RESOLVED 20/02/24:


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/a277506f-c720-475f-8096-665d19c772ee)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/0986e8c9-ebc8-468a-9e38-fc6c978f4c1d)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/f3a0ad76-8a02-43db-bcc3-a7af6fe7aaac)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/4ae10dc9-9cc9-41b5-a92a-6a9dde715362)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/5462294d-17ca-4a0b-a51f-7d7b1d860018)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/ca286918-64c0-4488-81db-eb744f9994a2)

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/b964df20-4d9a-4107-af6c-7da236767baa)
