### ISSUE TITLE
User Story: SO_17 Search Engine Optimisation (SEO) techniques

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#60]
EPIC:  Marketing #7 

* SO_17 As **System Owner** I want to **Employ Search Engine Optimisation (SEO) techniques** so as to **improve audience reach**

### Assumptions or Pre-Requisites:
* Site is developed and pages are stabilised

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Ensure that all pages on the site can be reached by a link from another findable page.
- [x] Include Meta Description tags in the application HTML **DONE 21/02/24**
- [x] Include a site title on the parent template
- [x] When defining the relationship between the current document and a linked document, ensure the following:
* Use “nofollow” for any paid links and distrusted content.
* Use “sponsored” for any sponsored or compensated links.
- [x] Include a sitemap on your application to allow search engine bot crawling **DONE 21/02/24**
- [x] Include a robots.txt file to control search engine bot crawling **DONE 21/02/24**

### Tasks
- [x] Task1 Check page links
- [x] Task2 Check Meta description tags
- [x] Task3 Check site title on base.html
- [x] Task4 Check for any paid or sponsored links on site (currently not applicable)
- [x] Task5 Build & include sitemap 
- [x] Task6 include robots.txt file
- [x] Task7 Control access to your sitemap via a robots.txt file
- [x] Task8 Verify All sitemap links are canonical.
- [x] Task9 Use descriptive metadata for SEO that accurately reflect the site’s purpose.

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion
