### ISSUE TITLE
User Story: Version 1 Deploy

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#61]
EPIC:  #7 

As a **system owner** I can **deploy and re-deploy the system with delivered functionality** so that **the site operates as expected with version 1 functionality**

### Assumptions or Pre-Requisites:
* MVP Deploy has been achived and any lessons learned incorporated

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to build/ redeploy app inHeroku
- [x] App must run as expected
- [x] SEO optimisation tecchniques are incorporated into V1 deployment
- [x] site is linked to-from fb business page

### Tasks:
- [x] Must be able to build/ redeploy app inHeroku
- [x] App must run as expected
- [x] SEO optimisation tecchniques are incorporated into V1 deployment #60
- [x] site is linked to-from fb business page #59 
- [x] Commit, build deployment
- [x] Test app
