### ISSUE TITLE
User Story: Site Validation

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#62]
EPIC:  #67 
SO_06 As **site owner** I want to **provide a website, which meets current programming, performance and accessibility standards (html, css, javascript, responsive, accessibility, performance)** so that **users can enjoy a high-standard experience**

### Assumptions or Pre-Requisites:
System has reached a stable point (note that some of these valiation tests may need to be repeated prior to handover)

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] All validation tests must be completed
- [ ] All validaton tests must pass, unless a reasonable explanation can be provided for failure

### Tasks
- [x] Task1 W3C validation of each html file (needs to be based on rendered, rather than source, html, as source includes non-html control codes)... using checker at [https://validator.w3.org/nu/#file](https://validator.w3.org/nu/#file)
* 20/02/24:  ONGOING (6 errors remaining in product detail; 7 errors in products:  mostly these refer to the navigation meny whcih has li as a child of nav)
* 21/02/24: 
- [ ] Task2 Accessibility checking of each customized HTML file using [https://wave.webaim.org/report#/](https://wave.webaim.org/report#/)
- [x] Task3 CSS testing of style.css using https://jigsaw.w3.org/css-validator/:  DONE 20/02/24 for base.css (4 errors: resolved)
- [x] Task4 Lighthouse testing of overall site in Chrome
- [x] Task5 Python PEP8 testing (all altered py files) using [CI's PEP8 validator](https://pep8ci.herokuapp.com/#)  
* NOPE using **python3 -m flake8** to validate multiple files in one go
- [x] Task6 User Testing and feedback

**Comment by DeeMcCart** [comment]
18/02/24 DMcC:
OK the best commands to use are:
python3 -m flake8 products --exclude=products/migrations/*.* (DONE 18/02:  just looks for issues with the products app)
python3 -m flake8 profiles --exclude=profiles/migrations/*.* (DONE 19/02- but user registration no longer working as expected???)
python3 -m flake8 checkout --exclude=checkout/migrations/*.* (DONE 19/02- but profiles no longer working as expected???)
1-1.5 hour per app.

**Comment by DeeMcCart** [comment]
Validation done but not satisfactory.  **In particular, last-minute HTML validation fix (header issue relating to button/anchor within <nav>/<ul>) caused knock-on problems which means the responsive display is now incorrect**.
HTML validation - completed successfully;
CSS validation - completed successfully; 
W3C accessibility validation - incomplete;
Lighthouse performance validation - done but very low scores in 70% range (even on rechecking) - this needs more investigation;
Python validation - completed with a couple of small remaining issues on 2 of the 4 apps.
Javascript validation - not done.
User testing/ test scripts - documentation presented is not reflective of the volume and variety of testing actually done.  Also certain functionality is not working at time of submission 
* feedback form not sending via emailjs; 
* reviews created are submitted for moderation without pulling through the review score; 
* issues with firefox display on android phone (not seen with chrome on android phone); 
* tracker # cannot be entered on order admin console)
HOWEVER, deadline reached therefore necessary to submit!
