### ISSUE TITLE
Task: Sprint 4 Retrospective, Sprint5 Planning:

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#65]
EPIC:  #10 

As a **scrum master/developer** I can **follow Agile principles** so that **project functionality is achieved incrementally across sprints**

### Assumptions or Pre-Requisites:
* Agile methodology is being followed for this project
* Closing out (weekly) sprint should be done with a retrospective
* Planning of next sprint should be done with backlog grooming and deciding which tasks to move to 'to do' for this sprint
* Respect timeboxing and not try to complete any tiny outstanding items from previous Sprint 'quickly' in the new Sprint. The time has passed so now deal with any hangover items in CURRENT sprint

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
* Sprint4 closed off (this happens automatically when using iterations)
* Any issues which were linked to Sprint4 but not in 'Done' status reviewed and
moved to next sprint for completion of outstanding tasks
* OR if the acceptance criteria is met and tasks done, but there are issues, then log the issues as a bug and closeout the original UserStory/ task

### Tasks
- [x] Task1 Retrospective
- [x] Task2 Backlog groominig
- [x] Task3 Sprint Planning and issue prioritisation
- [x] Task4 Update readme with work to date

**Comment by DeeMcCart** [comment]
**Task1 RETROSPECTIVE:**
Resumed work Tuesday 13/02 after 3 days away, took about a day to get back up to speed again.  Quite a few of the outstanding user stories tackled (but many incomplete).  Main progress was in:
* Deployment #56 - got the AWS deployment working correctly once I understood bucket security & need to manually load images.  Also resolved issues with user profile creation (however user profiles causing new issues since validation/other updates 19/02/24)
* Mentor meeting 2 - mid-point - managed Fri 16/02
* Reviews #57 - added the data structures & creation via Admin console, however need to add a front-end
* Product listing & management grid for sysadmin
* Order listing & management grid for sysadmin
* Consistent look & feel - allauth, sticky footer etc (DONE - but introduced new problems 19/02 with visibility of entire content)
* Validation - started with resolving python linting errors across c. 30 py files. (about half done, will need second pass)

**Comment by DeeMcCart** [comment]
![agile-retrospective-sprint4](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/0221424e-afb2-4717-8056-0ec28589e2db)
