### ISSUE TITLE
User Story: RU_13 Leave Reviews - remaining CRUD Tasks

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#66]
EPIC:  #24 

* RU_13 As a **Returning User** I would like to **create Product Reviews and ratings** to **increase interaction with the site and help to guide other purchasers**

### Assumptions or Pre-Requisites:
* Core functionality is up and running including Product and Product Detail views
* Product model includes an average review
* Product Models include reviews
* Product App has Reviews entry form per product

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] (Registered users) Must be able to leave a product review 
- Preferably if they have purchased the item in question? (NOPE - Decided to leave it available to all registered users as helpful comments may encourage other users to purchase....)
- [x] Reviews can be moderated and approved by the site administrator

### Tasks

- [x] Task3 Extend email confirmation to include a suggestion that the customer leaves a review
- [x] Task4 Add a review form where a registered customer can leave a review for a product they have purchased ('review' button appears beside any product they have purchased
- [x] Task5 Add a panel for sysadmin to view comments and approve them??  (Might not be necessary)

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Sprint4: The data structures and templates were put into place on read-only basis (can be CUD via Admin console only).  Sprint5 needs to address the remaining item if possible- review creation by end user, and revew approval by administrator.
