### ISSUE TITLE
EPIC: Validation & Documentation

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#67]
EPIC:  Validaton & Docuemtnation of Submitted PP5 Project

### Assumptions or Pre-Requisites:
*  Programming work is pretty much completed
*  
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] #62 systems valication must be completed
- [x] Review issue log
- [ ] Closeout any remaining bugs
- [x] #68 
- [x] #60 
- [x] #61 
- [x] #59 

### Tasks

- [x] Task1 #62 
- [x] Task2 #68
- [x] Task3 #60 
- [x] Task4 #61 
- [x] Task5 #59 
- [x] Task4 Review issue log
- [ ] Closeout any remaining bugs

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
8 of 139 bugs unresolved, see Sprint 5 Review #70  
ISSUE LOG is at https://docs.google.com/spreadsheets/d/1c03-8MvHUGg_ebzb8hMKn2PpbqHV23T5cvY5oasyAaE/edit?usp=sharing

Analysis of isssues at time of PP5 submission:
issues raised : 137**
issues closed: 97
future : 26
workaround: 6

8 issues remaining (bugs)
