### ISSUE TITLE
Task:  Fill out READme Doc

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#68]
As a **system designer** I can clearly explain **site purpose, features and design** so that the **intention, validation and delivered site** can be understood by an assessor

### Assumptions:
The site is pretty much in place, just needing some final tweaks (!!)

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Readme contains all necessary sections

### Tasks/ Sections:
- [x] Task1 UX Design  - added wireframes 19/02/24
- [x] Task2 Features - Added (23) Feature Titles/List 19/02/24 
- [x] Task3 Features <-> User Stories Mapping DONE
- [x] Task4 Features - Add Text **DONE but under-documented 03/03/24**
- [x] Task 5 - Deployment - Add section - DONE 19/02/24 18:00
- [x] Task 6 - Validation docs **DONE but under-documented 03/03/24**
- [x] Task7 - SEO Documentation **DONE 21/02/24**
- [x] Task8 - Deployments Section **DONE 19/02/24**
- [x] Database models - **Partly done 02/03/24 - Models documented but ERD missing**

**Comment by DeeMcCart** [comment]
DMcC 03/03/24 Would have liked to get this a bit more streamlined but wrestled with content vs time.
