### ISSUE TITLE
User Story:  First Deploy

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP5_Jeweller#8]
EPIC:  #7 

As a **system owner** I can **deploy and re-deploy the system** so that **I can apply continuous improvements to the site**

### Assumptions or Pre-Requisites:
* Basic site setup is in place #1 
* Debug mode set to FALSE

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [x] Must be able to build app in Heroku
- [x] Must be able to run app once built
- [x] CSS pulls through on displayed app

### Tasks

- [ ] Configure DEBUG = FALSE in settings.PY
- [x] python3 manage.py collectstatic (to put all the gubbins into the static folder)
- [x] commit with above settings (so that github is up to date with the workspace)
- [x] Add app in Heroku and assign name
- [x] Assign build dependencies to Heroku settings
- [x] Assign settigs - config variables in Heroku
- [x] Deploy branch main (do not set to auto redeply yet)
- [x] Use build logs to troubleshoot until deployment built
- [x] Test app

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
24/01/24:  first attempt - seemed to build the app but not run.
Realised I'd forgotten to set DEBUG = False
also attempted to use the command python3 manage.py collectstatic but it cancelled within the console?
--------------------
2nd attempt - set DEBUG = False and re-comitted.
Tried adding node.js to dependencies as thought this might be relevant (subsequently checked and NodeJS wasnt a dependency on Boutique Ado/Reloved projects)
Removed this depdency for 3rd attempt
---------------------
3rd attempt:  dependency is PythonJS only.
No config variables set.
Got errr:  File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
           raise ImproperlyConfigured("You're using the staticfiles app "
       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
--------------------------
4th attempt: set DISABLE_COLLECTSTATIC=1 on Heroku side.

**Comment by DeeMcCart** [comment]
4th attempt:  with DISABLE_COLLECTSTATIC=1 on Heroku config variables
App deploys OK but does not run (yikes, this feels familiar to me from last weeks Hackathon)
Heroku web Logs don't give a lot of information, so will try using the Heroku command-line interface instead

[240124 Heroku logs deploy 4th attempt.txt](https://github.com/DeeMcCart/CI_PP5_Jeweller/files/14037497/240124.Heroku.logs.deploy.4th.attempt.txt)

**Comment by DeeMcCart** [comment]
5th attempt:  OK making progress, can see that the 'Resource' tab on heroku now has the Procfile contents, and an attempt is made to run the server.  Gets a 400 error, I think this is becuase ALLOWED_HOSTS doesnt yet have the URL https://jeweller-bd1caeb15bbd.herokuapp.com/....

**Comment by DeeMcCart** [comment]
Kept working on this Friday 25/01/24 but still getting 500 error on the Heroku site, even though its deployed OK.  Checked through Slack to see if anyone came across it.  Suggestion:
settings.py: ACCOUNT_EMAIL_VERIFICATION = 'None' - this had been set to 'Mandatory'

**Comment by DeeMcCart** [comment]
Got a successful deploy when Debug=True, park this for now and review later:

![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/de08ac5a-62f1-4d32-8d59-f3d097eca40f)

**Comment by DeeMcCart** [comment]
However issues with the allauth templates:

attempt to see register prage:


![Image](https://github.com/DeeMcCart/CI_PP5_Jeweller/assets/126502176/12c045a7-d7b9-42e1-b263-f4d45db21339)



attempt to see login page

**Comment by DeeMcCart** [comment]
End of Sprint1 - Closing off this task and raising an isssue/bug for the error above.  Deployment has been created, even if not running successfully.

**Comment by DeeMcCart** [comment]
14/02/24 DMcC - Closing out this EPIC as believe done even if issues not fully resolved, has been surpassed b =y successive deploy using Amazon S3 backend for static files
